WebApp/Models/Entities/ContactFormEntity.cs
namespace WebApp.Models.Entities;

public class ContactFormEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public string Email { get; set; } = null!;
    public string Message { get; set; } = null!;
}

WebApp/Models/Entities/ProductEntity.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models.Entities;

public class ProductEntity
{
    public int Id { get; set; }
    public string Title { get; set; } = null!;
    public string? Description { get; set; }
    public string? ImageUrl { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    public ICollection<ProductTagEntity> ProductTags { get; set; } = new HashSet<ProductTagEntity>();
}

WebApp/Models/Entities/ProductTagEntity.cs
using Microsoft.EntityFrameworkCore;

namespace WebApp.Models.Entities;

[PrimaryKey("ProductId", "TagId")]
public class ProductTagEntity
{
    public int ProductId { get; set; }
    public ProductEntity Product { get; set; } = null!;
    public int TagId { get; set; }
    public TagEntity Tag { get; set; } = null!;
}

WebApp/Models/Entities/TagEntity.cs
namespace WebApp.Models.Entities;

public class TagEntity
{
    public int Id { get; set; }
    public string TagName { get; set; } = null!;

    public ICollection<ProductTagEntity> ProductTags { get; set; } = new HashSet<ProductTagEntity>();
}

WebApp/Models/Entities/UserProfileEntity.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models.Entities;

public class UserProfileEntity
{
    [Key, ForeignKey(nameof(User))]
    public string UserId { get; set; } = null!;
    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;
    public string? StreetName { get; set; } 
    public string? PostalCode { get; set; } 
    public string? City { get; set; } 

    public IdentityUser User { get; set; } = null!;
 
}

WebApp/ViewModels/ContactFormViewModel.cs
using WebApp.Models.Entities;

namespace WebApp.ViewModels
{
    public class ContactFormViewModel
    {
        public string Name { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string Message { get; set; } = null!;

        public static implicit operator ContactFormEntity(ContactFormViewModel viewModel)
        {
            return new ContactFormEntity
            {
                Name = viewModel.Name,
                Email = viewModel.Email,
                Message = viewModel.Message
            };
        }
    }
}

WebApp/ViewModels/HomeIndexViewModel.cs
namespace WebApp.ViewModels;

public class HomeIndexViewModel
{
    public ShowcaseViewModel Showcase_1 { get; set; } = null!;
    public ShowcaseViewModel Showcase_2 { get; set; } = null!;
}

WebApp/ViewModels/ShowcaseViewModel.cs
namespace WebApp.ViewModels;

public class ShowcaseViewModel
{
    public string? Ingress { get; set; }
    public string? Title { get; set; }
    public string? LinkContent { get; set; }
    public string? LinkUrl { get; set; }
    public string? ImageUrl { get; set; }
}

WebApp/ViewModels/UserSignInViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.ViewModels;

public class UserSignInViewModel
{

    [DataType(DataType.EmailAddress)]
    public string Email { get; set; } = null!;


    [DataType(DataType.Password)]
    public string Password { get; set; } = null!;

    public bool RememberMe { get; set; }

}

WebApp/ViewModels/UserSignUpViewModel.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using WebApp.Models.Entities;

namespace WebApp.ViewModels;

public class UserSignUpViewModel
{
    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;


    [DataType(DataType.EmailAddress)]
    public string Email { get; set; } = null!;

    public string? PhoneNumber { get; set; }


    [DataType(DataType.Password)]
    public string Password { get; set; } = null!;


    [DataType(DataType.Password)]
    [Compare(nameof(Password))]
    public string ConfirmPassword { get; set; } = null!;

    public string? StreetName { get; set; }

    public string? PostalCode { get; set; }

    public string? City { get; set; }


    public static implicit operator IdentityUser(UserSignUpViewModel model)
    {
        return new IdentityUser
        {
            UserName = model.Email,
            Email = model.Email,
            PhoneNumber = model.PhoneNumber
        };
    }

    public static implicit operator UserProfileEntity(UserSignUpViewModel model)
    {
        return new UserProfileEntity
        {
            FirstName = model.FirstName,
            LastName = model.LastName,
            StreetName = model.StreetName,
            PostalCode = model.PostalCode,
            City = model.City
        };
    }
}

WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers;

public class AccountController : Controller
{
    private readonly AuthService _auth;

    public AccountController(AuthService auth)
    {
        _auth = auth;
    }

 
    public IActionResult SignUp()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignUp(UserSignUpViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (await _auth.SignUpAsync(model))
                return RedirectToAction("SignIn");

            ModelState.AddModelError("", "User with the same email already exists");
        }
        return View(model);
    }



    public IActionResult SignIn()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignIn(UserSignInViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (await _auth.SignInAsync(model))
                return RedirectToAction("Index");

            ModelState.AddModelError("", "Incorrect email or password");
        }
        return View(model);
    }

    // Shows page if signed in
    [Authorize]
    public IActionResult Index()
    {
        return View();
    }


    [Authorize]
    public new async Task<IActionResult> SignOut()
    {
        if (await _auth.SignOutAsync(User))
            return LocalRedirect("/");

        return RedirectToAction("Index");

    }


}

WebApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Repositories;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactFormRepository _formRepository;

        public ContactsController(ContactFormRepository formRepository)
        {
            _formRepository = formRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _formRepository.AddAsync(viewModel);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }


    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

WebApp/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View(id);
        }
    }
}

WebApp/Views/Admin/Index.cshtml
@{ ViewData["Title"] = "Admin - Dashboard"; }
@inject UserManager<IdentityUser> userManager


<div>
    @{
        var users = userManager.Users.ToList(); // Load users into a separate list
    }

    @foreach (var user in users)
    {
        var roles = await userManager.GetRolesAsync(user); // Load roles for each user

        <div class="mb-5">
            <div>@user.Email</div>
            <div>
                @foreach (var role in roles)
                {
                    <div>@role</div>
                }
            </div>
        </div>
    }
</div>


<section class="admin-dashboard">
    <div class="container">
        <div class="title">Admin Dashboard</div>

        <div class="admin-grid">

            <div class="all-users">
                <button class="btn options">List Users</button>
            </div>


            <div class="add-product">
                <button class="btn options"> Add Products</button>
            </div>


            <div class="manage-users">
                <button class=" btn options">Manage Users</button>
            </div>

        </div>


    </div>
</section>

WebApp/Views/Contacts/Index.cshtml
@{
    ViewData["Title"] = "Contact Us";
}

<partial name="~/Views/Partials/_ContactForm.cshtml"/>

WebApp/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home"; }
@model HomeIndexViewModel

<partial name="/Views/Partials/_Showcase.cshtml" />
<partial name="/Views/Partials/_BestCollection.cshtml" />
<partial name="/Views/Partials/_SalesShowcase.cshtml" />
<partial name="/Views/Partials/_TopSelling.cshtml" />
<partial name="/Views/Partials/_Subscribe.cshtml" />

WebApp/Views/Partials/_BestCollection.cshtml
@inject ProductRepository productRepo

@{
    var productsWithTag2 = (await productRepo.GetAsync())
        .Where(p => p.ProductTags.Any(pt => pt.TagId == 2));
}

@if (productsWithTag2 != null && productsWithTag2.Any())
{
    <section class="best-collection">
        <div class="container">
            <div class="best-title">
                <h1>Best Collection</h1>
                <div class="categories">
                    <a class="category-link" href="#">All</a>
                    <a class="category-link" href="#">Bags</a>
                    <a class="category-link" href="#">Dress</a>
                    <a class="category-link" href="#">Decoration</a>
                    <a class="category-link" href="#">Essentials</a>
                    <a class="category-link" href="#">Interior</a>
                    <a class="category-link" href="#">Laptop</a>
                    <a class="category-link" href="#">Mobile</a>
                    <a class="category-link" href="#">Beauty</a>
                </div>
            </div>

            <div class="row row-cols-1 row-cols-md-4 g-4">
                @foreach (var product in productsWithTag2)
                {
                    <div class="col">
                        <a href="/Products/details/@product.Id">
                            <div class="card">
                                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                            </div>
                            <div class="product-description">
                                <div class="product-title">@product.Title</div>
                                <p class="price">$@product.Price.ToString("0.00")</p>
                            </div>
                        </a>
                    </div>
                }
            </div>

            <div class="best-btn">
                <button class="btn-white">SHOP NOW</button>
            </div>
        </div>
    </section>
}
else
{
    <div>
        No products found with TagId = 2
    </div>
}






<section class="best-collection">
    <div class="container">
        <div class="best-title">
            <h1>Best Collection</h1>
            <div class="categories">
                <a class="category-link" href="#">All</a>
                <a class="category-link" href="#">Bags</a>
                <a class="category-link" href="#">Dress</a>
                <a class="category-link" href="#">Decoration</a>
                <a class="category-link" href="#">Essentials</a>
                <a class="category-link" href="#">Interior</a>
                <a class="category-link" href="#">Laptop</a>
                <a class="category-link" href="#">Mobile</a>
                <a class="category-link" href="#">Beauty</a>
            </div>
        </div>



        <div class="row row-cols-1 row-cols-md-4 g-4">

            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Sneakers</div>
                    <p class="price">$30.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Necklace</div>
                    <p class="price">$12.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Airpods</div>
                    <p class="price">$95.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Cat Sweater</div>
                    <p class="price">$45.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Beanie</div>
                    <p class="price">$29.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Jacket</div>
                    <p class="price">$115.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Socks</div>
                    <p class="price">$15.00</p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Eyeshadow palette</div>
                    <p class="price">$30.00</p>
                </div>
            </div>
        </div>
        <div class="best-btn">
            <button class="btn-white">SHOP NOW</button>
        </div>
    </div>
</section>

WebApp/Views/Partials/_ContactForm.cshtml
@model ContactFormViewModel
@{
    ViewData["Title"] = "Contact Us";
}

<div class="d-flex justify-content-between ">
    <h1 class="display-4">Contact Us</h1>
    
</div>


<section class="contact-form ">
    <div class="container">
        <div class="title">@ViewData["Title"]</div>

        <form asp-action="Index" asp-controller="Contacts" method="post" class="col-10 col-xl-6">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label">First Name</label>
                <input asp-for="Name" class="form-control" />
                <small class="text-danger"><span asp-validation-for="Name"></span></small>
            </div>


            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <small class="text-danger"><span asp-validation-for="Email"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Message" class="form-label">Message</label>
                <textarea asp-for="Message" class="form-control"></textarea>
                <small class="text-danger"><span asp-validation-for="Message"></span></small>
            </div>

            <div class="mt-5">
                <div class="d-grid">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>

        </form>
        
    </div>
</section>

WebApp/Views/Partials/_Footer.cshtml
<footer>
    <div class="bottom-border">
        <p>© @DateTime.Now.Year bmarketo.  All right reserved.</p>
    </div>
</footer>

WebApp/Views/Partials/_Header.cshtml
<header>
    <div class="container">
        <div class="logo"><img src="images/logo.svg" alt="bmerketo"></div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="home" asp-action="Index">HOME</a>
            <a class="link" asp-controller="products" asp-action="Index">PRODUCTS</a>
            <a class="link" asp-controller="contacts" asp-action="Index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="products" asp-action="Search"><i class="fa-regular fa-search"></i></a>


            @if (signInManager.IsSignedIn(User))
            {
                <a class="link" asp-controller="shopping" asp-action="Cart"><i class="fa-solid fa-cart-shopping"></i></a>
                <a class="link" asp-controller="Account" asp-action="Index">@User.Identity?.Name</a>
                <a class="link" asp-controller="Account" asp-action="SignOut">Logout</a>
            }
            else
            {
                <a class="link" asp-controller="Account" asp-action="SignIn">Login</a>
                <a class="link" asp-controller="shopping" asp-action="Cart"><i class="fa-solid fa-cart-shopping"></i></a>
            }






        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

WebApp/Views/Partials/_SalesShowcase.cshtml
<section class="sales-showcase">
    <div class="container">
        <div class="sales-content">

            <div class="left-card">
                <div class="card">
                    <img src="images/placeholders/369x310.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Sneakers</div>
                    <p class="price">$30.00</p>
                </div>
            </div>


            <div class="sales-offer">
                <div class="highlight-text"> SPECIAL SALE </div>
                <div class="sales-amount">50% OFF</div>
                <div class="sales-title">Get The Best Price</div>
                <p>Get the best daily offer et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren no sea taki</p>
                <a class="discovery-link" href="#">Discover More</a>
            </div>

            <div class="right-card">
                <div class="card">
                    <img src="images/placeholders/369x310.svg" class="card-img-top" alt="...">
                </div>
                <div class="product-description">
                    <div class="product-title">Sneakers</div>
                    <p class="price">$30.00</p>
                </div>
            </div>
        </div>
    </div>
</section>

WebApp/Views/Partials/_Showcase.cshtml
@inject ShowcaseService showcaseService
@{
    var showcase = showcaseService.GetLatest();
}

@if (showcase != null)
{

    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="ingress">@showcase?.Ingress</div>
                <div class="title">@showcase?.Title</div>

                @if (!string.IsNullOrEmpty(showcase?.LinkUrl) && !string.IsNullOrEmpty(showcase?.LinkContent))
                {
                    <a href="/products" class="button btn-theme">@showcase?.LinkContent</a>
                }
            </div>
            <div>
                <img src="@showcase?.ImageUrl" alt="@showcase?.Title">
            </div>
        </div>
    </section>

}

WebApp/Views/Partials/_Subscribe.cshtml
<section class="subscribe-now">
    <div class="container">
        <div class="subscribe-title">
            <p>Sign up for our weekly newsletter</p>
            <div class="subscribe">
                <form id="subscribeForm">
                    <input id="subscriptionEmail" type="email" placeholder="Enter email address">
                    <button type="submit">Subscribe</button>
                </form>
            </div>
        </div>
    </div>
</section>

WebApp/Views/Partials/_TopSelling.cshtml
@inject ProductRepository productRepo

@{
    var topSellingProducts = (await productRepo.GetAsync())
        .Where(p => p.ProductTags.Any(pt => pt.TagId == 3))
        .Take(6); // Adjust the number of products to display here
}

@if (topSellingProducts != null && topSellingProducts.Any())
{
    <section class="top-selling">
        <div class="section-title">
            <h2>Top selling products this week</h2>
        </div>

        <div class="row row-cols-1 row-cols-md-6 g-4">
            @foreach (var product in topSellingProducts)
            {
                <div class="col">
                    <a href="/Products/details/@product.Id">
                        <div class="card">
                            <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
                        </div>
                        <div class="product-description">
                            <div class="product-title">@product.Title</div>
                            <p class="price">$@product.Price.ToString("0.00")</p>
                        </div>
                    </a>
                </div>
            }
        </div>

        <div class="slider-buttons">
            <button class="slider-btn btn-white"><i class="fa-solid fa-chevron-left"></i></button>
            <button class="slider-btn btn-white"><i class="fa-solid fa-chevron-right"></i></button>
        </div>
    </section>
}
else
{
    <div>
        No top-selling products found with TagId = 3
    </div>
}




<section class="top-selling">
    <div class="section-title">
        <h2>Top selling products this week</h2>
    </div>

    <div class="row row-cols-1 row-cols-md-6 g-4">

        <div class="col">
            <div class="card">
                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
            </div>
            <div class="product-description">
                <div class="product-title">Sneakers</div>
                <p class="price">$30.00</p>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
            </div>
            <div class="product-description">
                <div class="product-title">Sneakers</div>
                <p class="price">$30.00</p>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
            </div>
            <div class="product-description">
                <div class="product-title">Sneakers</div>
                <p class="price">$30.00</p>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
            </div>
            <div class="product-description">
                <div class="product-title">Sneakers</div>
                <p class="price">$30.00</p>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
            </div>
            <div class="product-description">
                <div class="product-title">Sneakers</div>
                <p class="price">$30.00</p>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="images/placeholders/270x295.svg" class="card-img-top" alt="...">
            </div>
            <div class="product-description">
                <div class="product-title">Sneakers</div>
                <p class="price">$30.00</p>
            </div>
        </div>
    </div>

    <div class="slider-buttons">
        <button class="slider-btn btn-white"><i class="fa-solid fa-chevron-left"></i></button>
        <button class="slider-btn btn-white"><i class="fa-solid fa-chevron-right"></i></button>

    </div>
</section>

WebApp/Views/Products/Details.cshtml
@model int
@inject ProductRepository productRepo

@{
    var product = await productRepo.GetAsync(x => x.Id == Model);
}





@if(product != null) {
    <div class="details">
        <div>@product.Title</div>
        <div>@product.Price</div>
        <div>
            @foreach (var tag in product.ProductTags)
            {
                <span class="me-2">@tag.Tag.TagName</span>
            }
        </div>
        <div>@product.Description</div>
    </div>
} else {
    <div>
        No product found
    </div>
}

WebApp/Views/Products/Index.cshtml
@inject ProductRepository productRepo


<section class="products-list">
    <div class="container">
        @foreach (var product in await productRepo.GetAsync())
        {
            <div>
                <div><a asp-action="details" asp-route-id="@product.Id">@product.Title</a></div>
                <div>
                    @foreach (var tag in product.ProductTags)
                    {
                        <span class="me-2">@tag.Tag.TagName</span>
                    }
                </div>
            </div>
           

        }
    </div>
</section>

WebApp/Views/Shared/_Header.cshtml
<div class="container mb-5">
    <div class="d-flex justify-content-between align-items-center m-4">
       
        
        <nav>
            <a asp-action="Index" asp-controller="Home" class="m-4">HOME</a>


            @if (signInManager.IsSignedIn(User) && User.IsInRole("admin"))
            {
                <a asp-action="Index" asp-controller="Admin" class="m-4">Admin</a>
            }
            
        </nav>
        <div>
            @if (signInManager.IsSignedIn(User))
            {
                <a asp-action="Index" asp-controller="Account">@User.Identity?.Name</a>
                <a asp-action="Index" asp-controller="Account">@User.FindFirst("DisplayName")?.Value</a>
                <a asp-action="SignOut" asp-controller="Account" class="m-4">SIGN OUT</a>
            }
            else
            {
                <a asp-action="SignUp" asp-controller="Account" class="m-4">SIGN UP</a>
                <a asp-action="SignIn" asp-controller="Account" class="m-4">SIGN IN</a>

            }
        </div>

    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bMerketo</title>
    <script src="https://kit.fontawesome.com/41c8b474e2.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.min.css" asp-append-version="true" />
</head>
<body>

    <partial name="/Views/Partials/_Header.cshtml" />

    @RenderBody()

    <partial name="/Views/Partials/_Footer.cshtml" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>